# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='user_name',
        ),
    ]
